# Site settings
title: CompSci 201 - Duke University
email: azhar@cs.duke.edu
description: This contains the assignments of CS201 at Duke University.
baseurl:  "" # the subpath of your site, e.g. /blog/
url: "http://www.cs.duke.edu" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

### NOTE: GitHub Pages requires Pygments, so switch the two lines when pushing ###
# highlighter: rouge
highlighter: pygments

assignments:
